apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels: 
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: kholeone/practical-project
        ports:
        - name: app-port 
        - containerPort: 5000
        env:
        - name: DATABASE_URI
          value: "mysql+pymysql://root:root@mysql:3306/listing"
---

apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: app
